### ISSUE TITLE
website typo and grammar

### ISSUE THREAD

**Issue by sureshvv** [upnotes-io/upnotes-website#9]
Use "a plain" not "plane" in "We believe that developers need more then just plane editor to capture the ideas and the context for any task".

Should be:

We believe that developers need more then just **a plain** editor to capture the ideas and the context for any task

**Comment by kamalkishor1991** [comment]
@sureshvv Thanks a lot for reporting. Fixed it now.
https://github.com/upnotes-io/upnotes-website/commit/8e7a35430b859e640e2a8bfbc75627ba005da757
